#!/bin/bash
#
# Checks if the code conforms to our coding standard
#
# Usage:
#
# ./scripts/do_clang_format
#
#

echo "----------------------------------------------------------------------------------------------------------------------------------------------"
echo "Your version                                                            | Corrected version"
echo "----------------------------------------------------------------------------------------------------------------------------------------------"

for filename in $(ls {*.cpp,*.h} | egrep -v "qrc_" | sort)
do
  echo "----------------------------------------------------------------------------------------------------------------------------------------------"
  echo "File: "$filename
  echo "----------------------------------------------------------------------------------------------------------------------------------------------"
  cp $filename current_code
  sed -i 's/!OCLINT/! OCLINT/g' current_code
  clang-format current_code > correct_code
  diff current_code correct_code --suppress-common-lines -y
done


