#!/bin/bash
#
# Checks if the code conforms to our coding standard
#
# Usage:
#
# ./scripts/do_clang_format
#
#
for filename in $(ls *.cpp | sort)
do
  echo "-----------------------------------------------------------------------"
  echo "File: $filename"
  echo "-----------------------------------------------------------------------"
  clang-format $filename > correct_code
  diff $filename correct_code --suppress-common-lines -y
done


