#!/bin/bash
#
# Checks if the code conforms to our coding standard
#
# Usage:
#
# ./scripts/do_clang_format
#
#
cat $(ls *cpp | sort) > current_code
clang-format current_code > correct_code ; diff current_code correct_code --suppress-common-lines -y

